typography_spectrum: 0.33002
color:
  brandColors:
    - '#171115'
    - '#ebeedd'
    - '#56383a'
    - '#9b5b38'
    - '#c79941'
  brandStrength: 0.75
  lightness: 0.8913300812710077
  saturation: 0.6600827388465405
  rhythmicContrast: 0.8319056185428053
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.24872
analytics:
  google: null
  facebook: null
  twitter: null
name: Bottom Up
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
